################ spring boot config ###############
server:
  port: 80
  servlet:
    context-path: /
management:
  endpoints:
    enabled-by-default: false             # 禁用所有actuator端点
  endpoint:
    health:
      enabled: true                       # 只开启必要的
spring:
  profiles:
    active: dev
  application:
    name: quant
  main:
    lazy-initialization: true             # 全局开启延迟初始化
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
forest:
  backend: okhttp3             # 后端HTTP框架 okhttp3 httpclient
  max-connections: 5000        # 连接池最大连接数（默认为 500）
  max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # 最大请求等待队列大小
  max-async-thread-size: 300   # 最大异步线程数
  max-async-queue-size: 16     # 最大异步线程池队列大小
  connect-timeout: 20000       # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 20000          # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 2           # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
  async-mode: platform         # 异步模式（默认为 platform）
  success-when: com.optimus.base.ForestSuccessCondition
  log-handler: com.optimus.base.ForestLogHandler

#====== config dev =======#
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    name: quant
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quant?rewriteBatchedStatements=true
    username: root
    password: 88888888
    hikari:
      pool-name: DatebookHikariCP
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000
      maximum-pool-size: 200
      minimum-idle: 50
logging:
  config: classpath:log4j2-dev.xml
  file:
    name: logs/game-platform-api.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
